[project]
name = "trabalho-pi"
version = "0.1.0"
description = ""
authors = [
    {name = "Breno Bertone",email = "bertonebreno@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pulp (>=3.3.2,<4.0.0)",
    "numpy (>=2.4.6,<3.0.0)"
]

[dependency-groups]
dev = [
    "pre-commit (>=4.6.0,<5.0.0)",
    "ruff (>=0.15.16,<0.16.0)",
    "mypy (>=2.1.0,<3.0.0)",
    "pytest (>=9.0.3,<10.0.0)"
]


[tool.ruff]
line-length = 88
target-version = "py313"

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.mypy]
python_version = "3.14"
strict = true
ignore_missing_imports = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
